cc_binary(
    name = "1_1",
    srcs = ["main.cpp"],
    deps = [
        "//mediapipe/calculators/core:pass_through_calculator",
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/port:parse_text_proto",
    ],
)
