cc_binary(
    name = "1_5",
    srcs = [
        "goblin_calculator15.cpp",
        "main.cpp",
    ],
    deps = [
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/port:parse_text_proto",
    ],
)
